#mensaje = "hola mundo"

eureka:
	client:
	service-url:
		defaultZone: http://localhost:5001/eureka/

#mysql.url = 172.17.0.5
#mysql.port = 3306


#spring.datasource.driver.class-name= com.mysql.jdbc.Driver
#spring.datasource.url= jdbc:mysql://localhost:3306/disenoweb?zeroDateTimeBehavior=convertToNull
#spring.datasource.username = root
#spring.datasource.password = Jsebastian5090
#spring.datasource.test-while-idle = true
#spring.datasource.validation-query = SELECT 1
#spring.datasource.max-wait = 10000
#spring.datasource.max-active = 300
#spring.datasource.test-on-borrow = true

#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
#spring.show-sql = true
