eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.28.133:5001/eureka/

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.17.0.2:3306/dsweb?zeroDateTimeBehavior=convertToNull
        username: root
        password: dsweb
        test-while-idle: true
        validation-query: SELECT 1
        max-wait: 10000
        max-active: 300
        test-on-borrow: true
        
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true